### ISSUE TITLE
Can you patch methods ?

### ISSUE THREAD

**Issue by dvtkrlbs** [Shizcow/hotpatch#1]
Your project looks really interesting and i will definitely experiment with it. What i was wondering was can you patch methods ?

**Comment by Shizcow** [comment]
Unfortunately no, not yet. The backend is much more complicated, and I'm not entirely sure if it's possible.

That said I haven't explored all options yet. After I take a break in this crate I'll be giving method hotpatching another try.

**Comment by dvtkrlbs** [comment]
Should i left this issue open for tracking this feature or should i close it ?

**Comment by Shizcow** [comment]
I'll close as willfix at a later date.
