### ISSUE TITLE
Is this library nightly only?

### ISSUE THREAD

**Issue by tekjar** [Shizcow/hotpatch#14]
Hi. I'm facing this error on stable 1.50

```
error[E0554]: `#![feature]` may not be used on the stable release channel
 --> /home/tekjar/.cargo/git/checkouts/hotpatch-6d47e0c925964dfc/702236c/hotpatch_macros/src/lib.rs:1:1
  |
1 | #![feature(proc_macro_diagnostic)]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

Is this library nightly only?

**Comment by extrawurst** [comment]
well the readme says this: `properly document nightly feature requirements`

**Comment by tekjar** [comment]
@extrawurst That gave me an impression that default features should work on stable. Hence trying to clarify

**Comment by Shizcow** [comment]
Yes, all useful parts of this library are nightly only. This library fundamentally cannot work without `fn_traits`, which are still in nightly. Until that feature makes it to stable there are no plans to separate features.

Closing with a note that I'll make the distinction more clear in the readme. Further discussion is welcome.
